### ISSUE TITLE
LGS Puan Hesabı Formülü

### ISSUE THREAD

**Issue by mustafaaydn** [RedS-DEV/php-lgspuanhesaplama#1]
Merhabalar, 

Öncelikle elinize sağlık gayet yararlı bir çalışma olmuş. Acaba

https://github.com/RedS-DEV/php-lgspuanhesaplama/blob/845bc1aa47d0be49400c753f3b6029dd7c76345e/index.php#L32

burada geçen netlerden puan hesabının yapıldığı formülü nasıl edindiğinizi paylaşabilir misiniz?

**Comment by RedS-DEV** [comment]
Merhaba,
Formülü hesaplama için kullanılan bir Excel belgesinde buldum. Google'da en üstte çıkan siteler de hesaplama yaptım, bir de bu formülle yaptım ve sonuçlar çok yakın çıkınca mobil uygulamamda kullandım. Daha sonra PHP sürümünü yaparken de mobil uygulamada ki formülü kullandım. Fakat İnkılap ile Din dersinin katsayıları karışmış, şimdi düzeltiyorum.

**Comment by RedS-DEV** [comment]
Düzeltildi: 6a153b9a148112472c5174241739e05c6e93ece4
